name: Deploy to FTP Server

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy files to FTP server
      - name: Upload files via FTP
        uses: appleboy/ftp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }} # Default port is 21
          local_dir: ./ # Directory to upload from (root of the repository)
          remote_dir: /htdocs/ # Directory on the FTP server to upload to
